### ISSUE TITLE
Outdated team manual on domjudge.org

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge-scripts#107]
The team manual at: https://www.domjudge.org/documentation -> button `team manual` is outdated. We should consider using the one from demoweb.

**Comment by eldering** [comment]
I think the underlying question should be solved: why was it outdated?
It should be part of the release process to add the latest manual to the website.

**Comment by thijskh** [comment]
It was outdated because it linked to the old release process and the leftover file was not removed so it was not detected that this was not current. I've linked it to the new location in my commit.

**Comment by eldering** [comment]
Ok, sorry, I hadn't checked that.
