### ISSUE TITLE
Change Ansible to have (way) less local modifications every time

### ISSUE THREAD

**Issue by nickygerritsen** [DOMjudge/domjudge-scripts#44]
Currently we have many local modifications for every contest, which is less than ideal. I suggest to do several things:
* Put changes related to having a graphical interface on the machines behind a flag so we don't have to comment them out for server-only hardware.
* Allow to change/overwrite values in `all.yml` somehow (different file which is in `.gitignore`?).
* Allow to specify hosts without the file being modified (create `hosts.example` and put `hosts` in `.gitignore`?).

Additionally, we might want to rename the `icpc-wf` folder, since we use it for way more. Maybe even either move the `ansible` folder one directory up or put it in a separate repository (which breaks some symlinks)?

**Comment by vmcj** [comment]
> Currently we have many local modifications for every contest, which is less than ideal. I suggest to do several things:
> 
>     * Put changes related to having a graphical interface on the machines behind a flag so we don't have to comment them out for server-only hardware.
I would say a role works better, but yes.
> 
>     * Allow to change/overwrite values in `all.yml` somehow (different file which is in `.gitignore`?).
I propose the following directories: `defaults` and `vars` where vars contains the `.gitignore`
> 
>     * Allow to specify hosts without the file being modified (create `hosts.example` and put `hosts` in `.gitignore`?).
> 
> 
> Additionally, we might want to rename the `icpc-wf` folder, since we use it for way more. Maybe even either move the `ansible` folder one directory up or put it in a separate repository (which breaks some symlinks)?
I think it makes sense to move domlogo and ansible to their own repo, in that case we can use a git submodule I think.

**Comment by vmcj** [comment]
@nickygerritsen I think this is fixed?

**Comment by nickygerritsen** [comment]
Yes
