### ISSUE TITLE
bin/dump-db overwrites existing files

### ISSUE THREAD

**Issue by vmcj** [DOMjudge/domjudge-scripts#78]
We should add a confirmation for this to make sure we actually want to overwrite that specific backup

**Comment by thijskh** [comment]
Where is this script

**Comment by vmcj** [comment]
https://github.com/DOMjudge/domjudge-scripts/blob/9f1a7ab1f984ac504624a485569bc3fa7ecf5394/provision-contest/ansible/roles/mysql_server/files/dump-db
